-- Insert 20 new listen_repeat tasks and 20 new interview tasks
-- Audio URLs use existing placeholder pattern (TTS fallback handles them)

INSERT INTO toefl_tasks (audio_url, transcript, category, difficulty, topic_domain, prep_time_seconds, record_time_seconds) VALUES
-- Listen & Repeat (20 tasks)
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'The university bookstore is having a sale on textbooks this week.', 'listen_repeat', 'easy', 'campus', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 'Please remember to bring your student ID card to the examination hall.', 'listen_repeat', 'easy', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 'The biology lab will be closed for maintenance on Tuesday afternoon.', 'listen_repeat', 'easy', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', 'Student parking permits must be renewed before the end of the month.', 'listen_repeat', 'easy', 'campus', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3', 'The dining hall now offers vegan and gluten-free meal options every day.', 'listen_repeat', 'easy', 'campus', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3', 'According to the syllabus, the final paper is due on the last day of classes.', 'listen_repeat', 'medium', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3', 'The professor suggested that students form study groups to prepare for the upcoming quiz.', 'listen_repeat', 'medium', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3', 'International students are encouraged to attend the orientation session on Friday morning.', 'listen_repeat', 'medium', 'campus', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3', 'The library has extended its hours during finals week to accommodate more students.', 'listen_repeat', 'medium', 'campus', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3', 'Peer tutors are available in the writing center from nine to five on weekdays.', 'listen_repeat', 'medium', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3', 'The career services office recommends updating your resume before attending the job fair next month.', 'listen_repeat', 'medium', 'work', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3', 'Students who miss more than three classes without a valid excuse may receive a lower participation grade.', 'listen_repeat', 'medium', 'academic', 15, 30),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3', 'The environmental science department is organizing a field trip to study local ecosystems next weekend.', 'listen_repeat', 'hard', 'academic', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3', 'Research published in the journal suggests that bilingual individuals demonstrate enhanced cognitive flexibility and problem-solving abilities compared to monolingual speakers.', 'listen_repeat', 'hard', 'academic', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3', 'The administration announced that tuition fees will increase by three percent starting next semester, citing rising operational costs and infrastructure investments.', 'listen_repeat', 'hard', 'campus', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3', 'Critics argue that standardized testing fails to accurately measure a student''s critical thinking abilities, creativity, and real-world problem-solving skills.', 'listen_repeat', 'hard', 'education', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3', 'The anthropology lecture series will explore how cultural practices shape economic behavior in developing nations over the next five weeks.', 'listen_repeat', 'hard', 'academic', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-18.mp3', 'Although renewable energy sources have gained popularity, many experts believe that fossil fuels will continue to dominate global energy production for at least another two decades.', 'listen_repeat', 'hard', 'society', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-19.mp3', 'The symposium on artificial intelligence ethics will feature speakers from MIT, Stanford, and Oxford who will discuss algorithmic bias and data privacy concerns.', 'listen_repeat', 'hard', 'technology', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-20.mp3', 'Despite numerous studies linking sleep deprivation to decreased academic performance, many university students continue to sacrifice rest in favor of completing assignments and preparing for examinations.', 'listen_repeat', 'hard', 'health', 15, 45);

INSERT INTO toefl_tasks (audio_url, transcript, category, difficulty, topic_domain, prep_time_seconds, record_time_seconds) VALUES
-- Interview Questions (20 tasks)
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'Talk about a hobby you enjoy and explain why it is important to you.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 'Describe your favorite season of the year and explain what you like to do during that time.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 'Who is someone you admire? Describe this person and explain why you look up to them.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', 'Talk about a book or movie that you recently enjoyed and explain why you liked it.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3', 'Describe a typical day in your life and explain what you enjoy most about your routine.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3', 'What kind of music do you like? Describe your favorite type of music and explain how it makes you feel.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3', 'Do you prefer to study in the morning or at night? Explain your preference with specific reasons.', 'interview', 'easy', 'education', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3', 'Talk about a recent trip you took. Where did you go and what did you do there?', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3', 'What is your favorite type of food? Describe it and explain why you enjoy it.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3', 'Describe your hometown and explain what makes it a special place to live or visit.', 'interview', 'easy', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3', 'Some students prefer to take classes online, while others prefer in-person instruction. Which do you prefer and why?', 'interview', 'medium', 'education', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3', 'Do you think it is better to have a job with a high salary but long hours, or a lower salary with better work-life balance? Explain your choice.', 'interview', 'medium', 'work', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3', 'Many people believe that traveling abroad is the best way to learn about different cultures. Do you agree or disagree? Give specific reasons.', 'interview', 'medium', 'life_choice', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3', 'Should governments spend more money on public transportation or on building new roads? Explain your position with examples.', 'interview', 'medium', 'society', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3', 'Some people think that social media has improved communication, while others believe it has made people more isolated. What is your opinion?', 'interview', 'medium', 'technology', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3', 'Is it more important for schools to teach students practical skills or academic knowledge? Explain your answer with specific examples.', 'interview', 'medium', 'education', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3', 'In your opinion, what is the most important quality a good leader should have? Support your answer with examples.', 'interview', 'medium', 'work', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-18.mp3', 'Do you think people should be required to recycle? Explain why or why not, using specific reasons and examples.', 'interview', 'medium', 'society', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-19.mp3', 'Some universities require students to take courses outside their major to become well-rounded. Do you think this is a good idea? Explain your position.', 'interview', 'medium', 'education', 15, 45),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-20.mp3', 'Many cities are experiencing housing crises due to rapid population growth and rising costs. What solutions would you propose to address this issue, and why do you think they would be effective?', 'interview', 'hard', 'society', 15, 60),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'With the rise of artificial intelligence, many workers fear losing their jobs to automation. Do you think governments should provide universal basic income to protect citizens, or should they focus on retraining programs? Use specific reasons to support your view.', 'interview', 'hard', 'technology', 15, 60),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 'Climate change is one of the most pressing issues of our time. Some argue that individual actions like recycling and reducing meat consumption are sufficient, while others believe that systemic changes by corporations and governments are necessary. What is your stance?', 'interview', 'hard', 'society', 15, 60),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 'The cost of higher education has risen dramatically in recent decades, leading many students to take on significant debt. Should universities be required to lower tuition, or should alternative models like income-share agreements replace traditional student loans? Explain your reasoning.', 'interview', 'hard', 'education', 15, 60),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', 'In many countries, the gap between the wealthy and the poor continues to widen. Some economists advocate for higher taxes on the rich to fund social programs, while others argue this discourages innovation and investment. Which approach do you support, and why?', 'interview', 'hard', 'society', 15, 60),
('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3', 'Remote work became widespread during the pandemic and remains popular today. However, some companies are now requiring employees to return to the office. Do you think remote work should be a permanent option for all jobs that can be done from home? Provide specific arguments.', 'interview', 'hard', 'work', 15, 60);
